package:
  name: whatsmyversion
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - whatsmyversion

about:
  home: http://github.com/ericdill/whatsmyversion
  license: GPLv3
